export const products = [
  {
    id: "p1",
    name: "Yağ Filtri Bosch 0451103313",
    slug: "yag-filtri",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    href: "/product/yag-filtri",
    imageSrc: "/assets/images/products_images/aments_products_image_1.jpg",
    price: "139.35 AZN",
    code: "BST-9922",
    oem_code: "0451103313",
    brand: { id: 1, name: "Bosch", slug: "bosch" },
    mark: { id: 1, name: "Tesla", slug: "tesla" },
    model: { id: 2, name: "Model S", slug: "model-s" },
    categoryId: 3,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_1.jpg", brand: "OilPR", code: "3244t54t", name: "Kapot", warehouse: "Xırdalan", qty: 1, price: "139.35 AZN" },
          { img: "/assets/images/products_images/aments_products_image_1.jpg", brand: "OilPR", code: "3244t54t", name: "Kapot", warehouse: "Babək", qty: 3, price: "139.35 AZN" },
        ],
      },
      {
        title: "Əvəzləyici",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_2.jpg", brand: "MANDO", code: "BN3244t54t", name: "Kapot", warehouse: "Babək", qty: 0, price: "188.96 AZN" },
          { img: "/assets/images/products_images/aments_products_image_2.jpg", brand: "MANDO", code: "BN3244t54t", name: "Kapot", warehouse: "Xırdalan", qty: 1, price: "188.96 AZN" },
        ],
      },
    ],
  },
  {
    id: "p2",
    name: "Təkər",
    slug: "teker",
    description: "Təkər üçün mock təsvir.",
    href: "/product/teker",
    imageSrc: "/assets/images/products_images/aments_products_image_2.jpg",
    price: "49.00 AZN",
    compareAt: "55.00 AZN",
    code: "TYR-2025",
    oem_code: "oem8659303",
    brand: { id: 2, name: "WheelPro", slug: "wheelpro" },
    mark: { id: 2, name: "Toyota", slug: "toyota" },
    model: { id: 3, name: "Corolla", slug: "corolla" },
    categoryId: 1,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_2.jpg", brand: "WheelPro", code: "TYR-2025", name: "Təkər", warehouse: "Babək", qty: 4, price: "49.00 AZN" },
          { img: "/assets/images/products_images/aments_products_image_2.jpg", brand: "WheelPro", code: "TYR-2025", name: "Təkər", warehouse: "Xırdalan", qty: 2, price: "49.00 AZN" },
        ],
      },
    ],
  },
  {
    id: "p3",
    name: "Mator",
    slug: "motor",
    description: "Mator üçün mock təsvir.",
    href: "/product/motor",
    imageSrc: "/assets/images/products_images/aments_products_image_3.jpg",
    price: "350.00 AZN",
    compareAt: "420.00 AZN",
    code: "ENG-7788",
    oem_code: "oem6863572",
    brand: { id: 3, name: "MotorLab", slug: "motorlab" },
    mark: { id: 3, name: "BMW", slug: "bmw" },
    model: { id: 4, name: "X5", slug: "x5" },
    categoryId: 2,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_3.jpg", brand: "MotorLab", code: "ENG-7788", name: "Mator", warehouse: "Xırdalan", qty: 1, price: "350.00 AZN" },
        ],
      },
      {
        title: "Əvəzləyici",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_4.jpg", brand: "ALT", code: "ALT-7788", name: "Mator", warehouse: "Babək", qty: 1, price: "420.00 AZN" },
        ],
      },
    ],
  },
  {
    id: "p4",
    name: "Akkumulyator",
    slug: "akkumulyator",
    description: "Akkumulyator üçün mock təsvir.",
    href: "/product/akkumulyator",
    imageSrc: "/assets/images/products_images/aments_products_image_4.jpg",
    price: "95.00 AZN",
    compareAt: "110.00 AZN",
    code: "BAT-110",
    oem_code: "oem5467844",
    brand: { id: 4, name: "PowerMax", slug: "powermax" },
    mark: { id: 4, name: "Hyundai", slug: "hyundai" },
    model: { id: 5, name: "Elantra", slug: "elantra" },
    categoryId: 2,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_4.jpg", brand: "PowerMax", code: "BAT-110", name: "Akkumulyator", warehouse: "Babək", qty: 5, price: "95.00 AZN" },
        ],
      },
    ],
  },
  {
    id: "p5",
    name: "Far",
    slug: "far",
    description: "Far üçün mock təsvir.",
    href: "/product/far",
    imageSrc: "/assets/images/products_images/aments_products_image_5.jpg",
    price: "120.00 AZN",
    compareAt: "150.00 AZN",
    code: "LAMP-500",
    oem_code: "oem6786733",
    brand: { id: 5, name: "LuxLight", slug: "luxlight" },
    mark: { id: 5, name: "Mercedes", slug: "mercedes" },
    model: { id: 6, name: "C200", slug: "c200" },
    categoryId: 3,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_5.jpg", brand: "LuxLight", code: "LAMP-500", name: "Far", warehouse: "Xırdalan", qty: 2, price: "120.00 AZN" },
        ],
      },
    ],
  },
  {
    id: "p6",
    name: "Şok Absorber",
    slug: "shock-absorber",
    description: "Şok absorber üçün mock təsvir.",
    href: "/product/shock-absorber",
    imageSrc: "/assets/images/products_images/aments_products_image_6.jpg",
    price: "80.00 AZN",
    compareAt: "99.00 AZN",
    code: "SHK-080",
    oem_code: "oem9990001",
    brand: { id: 6, name: "RideFlex", slug: "rideflex" },
    mark: { id: 6, name: "Kia", slug: "kia" },
    model: { id: 7, name: "Sportage", slug: "sportage" },
    categoryId: 1,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_6.jpg", brand: "RideFlex", code: "SHK-080", name: "Şok Absorber", warehouse: "Babək", qty: 1, price: "80.00 AZN" },
        ],
      },
    ],
  },
  {
    id: "p7",
    name: "Yağ Filteri",
    slug: "yag-filteri",
    description: "Yağ filteri üçün mock təsvir.",
    href: "/product/yag-filteri",
    imageSrc: "/assets/images/products_images/aments_products_image_7.jpg",
    price: "12.50 AZN",
    compareAt: "15.00 AZN",
    code: "OIL-F12",
    oem_code: "oem9990002",
    brand: { id: 7, name: "FilterX", slug: "filterx" },
    mark: { id: 7, name: "Nissan", slug: "nissan" },
    model: { id: 8, name: "X-Trail", slug: "x-trail" },
    categoryId: 2,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_7.jpg", brand: "FilterX", code: "OIL-F12", name: "Yağ Filteri", warehouse: "Xırdalan", qty: 10, price: "12.50 AZN" },
        ],
      },
    ],
  },
  {
    id: "p8",
    name: "Şam",
    slug: "sham",
    description: "Şam üçün mock təsvir.",
    href: "/product/sham",
    imageSrc: "/assets/images/products_images/aments_products_image_8.jpg",
    price: "9.90 AZN",
    compareAt: "11.50 AZN",
    code: "PLG-009",
    oem_code: "oem9990003",
    brand: { id: 8, name: "SparkIt", slug: "sparkit" },
    mark: { id: 8, name: "Ford", slug: "ford" },
    model: { id: 9, name: "Focus", slug: "focus" },
    categoryId: 3,
    offerGroups: [
      {
        title: "Axtarılan kod",
        rows: [
          { img: "/assets/images/products_images/aments_products_image_8.jpg", brand: "SparkIt", code: "PLG-009", name: "Şam", warehouse: "Babək", qty: 8, price: "9.90 AZN" },
        ],
      },
    ],
  },
];
