export const STATIC_CONTENT_MOCK = {
  en: {
    header__topWelcomeText: "Welcome to our store!",
    "header__topLink__login": "Login",
    "header__topLink__register": "Register",
    "header__topLink__my-account": "My Account",
    "header__topLink__admin-panel": "Admin Panel",
    header__logout: "Logout",
    header__searchPlaceholder: "OEM...",
    directorLoginBanner__sectionHead__button: "Continue",
    breadcrumb__home: "Home",
    breadcrumb__products: "Products",
    common__loading: "Loading...",
    common__noResults: "No results found",
    common__required: "Required",
    common__increase: "Increase",
    common__decrease: "Decrease",
    common__productAlt: "Product",
    pagination__previous: "Previous",
    pagination__next: "Next",
    catalog__oemLabel: "OEM:",
    catalog__similarFallbackMessage: "No exact product found, showing similar OEM results.",
    catalog__emptyMessage: "Product not found",
    catalog__filterTitle: "Filter",
    catalog__categoryPlaceholder: "Category",
    catalog__brandPlaceholder: "Brand",
    catalog__markPlaceholder: "Mark",
    catalog__modelPlaceholder: "Model",
    catalog__searchPlaceholder: "Search",
    catalog__searchButton: "Search",
    catalog__clearButton: "Clear",
    catalogList__searchTitle: "Search",
    catalogList__searchByNamePlaceholder: "Search by name",
    catalogList__categoriesTitle: "Categories",
    catalogList__showingResults: "Showing {count} results",
    offers__brandLabel: "Brand",
    offers__all: "All",
    offers__search: "Search",
    offers__reset: "Reset",
    offers__detail: "Detail",
    offers__warehouse: "Warehouse",
    offers__price: "Price",
    offers__add: "ADD",
    offerModal__qtyLabel: "Quantity",
    offerModal__amountLabel: "Amount",
    offerModal__noteLabel: "If you have notes, enter them.",
    offerModal__deliveryDateLabel: "Delivery date:",
    offerModal__deliveryDateValue: "30 April",
    offerModal__addToCart: "ADD TO CART",
    offerModal__addedToCartToast: "Added to cart successfully",
    addToCartModal__successMessage: "Added to cart successfully!",
    addToCartModal__viewCart: "View Cart",
    addToCartModal__checkout: "Checkout",
    addToCartModal__itemsInCart: "There are {count} items in your cart.",
    addToCartModal__totalPriceLabel: "TOTAL PRICE:",
    addToCartModal__continueShopping: "CONTINUE SHOPPING",
    product__similarBadge: "Similar OEM",
    product__viewOffersAria: "View offers",
    product__listDescriptionMock:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad, iure incidunt. Ab consequatur temporibus non eveniet inventore doloremque necessitatibus sed, ducimus quisquam, ad asperiores",
    productDetails__brand: "Brand",
    productDetails__mark: "Mark",
    productDetails__model: "Model",
    productDetails__code: "Code",
    productDetails__oem: "OEM",
    productDetails__similarOem: "Similar OEM",
    productDetailsPage__notFound: "Product not found",
    notFound__breadcrumbTitle: "404 Pages",
    notFound__headline: "Opps! PAGE NOT BE FOUND",
    notFound__messageLine1: "Sorry but the page you are looking for does not exist, have been",
    notFound__messageLine2: "removed, name changed or is temporarily unavailable.",
    notFound__searchPlaceholder: "Search entire store here ...",
    notFound__searchAria: "Search",
    notFound__backToHome: "Back to home page",
    faq__breadcrumbTitle: "FAQ",
    faq__headline: "Below are frequently asked questions, you may find the answer for yourself",
    faq__intro:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id erat sagittis, faucibus metus malesuada, eleifend turpis. Mauris semper augue id nisl aliquet, a porta lectus mattis. Nulla at tortor augue. In eget enim diam. Donec gravida tortor sem, ac fermentum nibh rutrum sit amet. Nulla convallis mauris vitae congue consequat. Donec interdum nunc purus, vitae vulputate arcu fringilla quis. Vivamus iaculis euismod dui.",
    contact__breadcrumbTitle: "Contact Us",
    contact__mapTitle: "Map",
    contact__addressLine1: "Address goes here,",
    contact__addressLine2: "street, Crossroad 123.",
    contact__followUs: "Follow Us",
    contact__facebook: "Facebook",
    contact__twitter: "Twitter",
    contact__youtube: "YouTube",
    contact__googlePlus: "Google Plus",
    contact__instagram: "Instagram",
    contact__getInTouch: "Get In Touch",
    contact__name: "Name",
    contact__email: "Email",
    contact__subject: "Subject",
    contact__yourMessage: "Your Message",
    contact__send: "SEND",
    cart__breadcrumbTitle: "Cart",
    cart__delete: "Delete",
    cart__image: "Image",
    cart__product: "Product",
    cart__price: "Price",
    cart__total: "Total",
    cart__empty: "Cart is empty",
    cart__update: "update cart",
    cart__totals: "Cart Totals",
    cart__subtotal: "Subtotal",
    cart__proceedToCheckout: "Proceed to Checkout",
  },
  az: {
    header__topWelcomeText: "Mağazamıza xoş gəlmisiniz!",
    "header__topLink__login": "Daxil ol",
    "header__topLink__register": "Qeydiyyat",
    "header__topLink__my-account": "Hesabım",
    "header__topLink__admin-panel": "Admin Panel",
    header__logout: "Çıxış",
    header__searchPlaceholder: "OEM...",
    directorLoginBanner__sectionHead__button: "Davam et",
    breadcrumb__home: "Ana səhifə",
    breadcrumb__products: "Məhsullar",
    common__loading: "Yüklənir...",
    common__noResults: "Nəticə tapılmadı",
    common__required: "Mütləqdir",
    common__increase: "Artır",
    common__decrease: "Azalt",
    common__productAlt: "Məhsul",
    pagination__previous: "Əvvəlki",
    pagination__next: "Növbəti",
    catalog__oemLabel: "OEM:",
    catalog__similarFallbackMessage: "Uyğun məhsul tapılmadı, oxşar OEM nəticələri göstərilir.",
    catalog__emptyMessage: "Məhsul tapılmadı",
    catalog__filterTitle: "Filter",
    catalog__categoryPlaceholder: "Kateqoriya",
    catalog__brandPlaceholder: "Brend",
    catalog__markPlaceholder: "Marka",
    catalog__modelPlaceholder: "Model",
    catalog__searchPlaceholder: "Axtarış",
    catalog__searchButton: "Axtar",
    catalog__clearButton: "Təmizlə",
    catalogList__searchTitle: "Axtarış",
    catalogList__searchByNamePlaceholder: "Ada görə axtar",
    catalogList__categoriesTitle: "Kateqoriyalar",
    catalogList__showingResults: "{count} nəticə göstərilir",
    offers__brandLabel: "Brend",
    offers__all: "Hamısı",
    offers__search: "Axtar",
    offers__reset: "Sıfırla",
    offers__detail: "Detal",
    offers__warehouse: "Anbar",
    offers__price: "Qiymət",
    offers__add: "ƏLAVƏ ET",
    offerModal__qtyLabel: "Miqdar",
    offerModal__amountLabel: "Məbləğ",
    offerModal__noteLabel: "Qeydləriniz varsa daxil edin.",
    offerModal__deliveryDateLabel: "Çatdırılma tarixi:",
    offerModal__deliveryDateValue: "30 aprelə",
    offerModal__addToCart: "SƏBƏTƏ AT",
    offerModal__addedToCartToast: "Səbətə uğurla əlavə edildi",
    addToCartModal__successMessage: "Səbətə uğurla əlavə edildi!",
    addToCartModal__viewCart: "Səbətə bax",
    addToCartModal__checkout: "Sifariş et",
    addToCartModal__itemsInCart: "Səbətdə {count} məhsul var.",
    addToCartModal__totalPriceLabel: "CƏM MƏBLƏĞ:",
    addToCartModal__continueShopping: "ALIŞVERİŞƏ DAVAM ET",
    product__similarBadge: "Oxşar OEM",
    product__viewOffersAria: "Təkliflərə bax",
    product__listDescriptionMock:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad, iure incidunt. Ab consequatur temporibus non eveniet inventore doloremque necessitatibus sed, ducimus quisquam, ad asperiores",
    productDetails__brand: "Brend",
    productDetails__mark: "Marka",
    productDetails__model: "Model",
    productDetails__code: "Kod",
    productDetails__oem: "OEM",
    productDetails__similarOem: "Oxşar OEM",
    productDetailsPage__notFound: "Məhsul tapılmadı",
    notFound__breadcrumbTitle: "404 Səhifə",
    notFound__headline: "Səhifə tapılmadı",
    notFound__messageLine1: "Axtardığınız səhifə mövcud deyil,",
    notFound__messageLine2: "silinib, adı dəyişdirilib və ya müvəqqəti əlçatmazdır.",
    notFound__searchPlaceholder: "Sayt üzrə axtar ...",
    notFound__searchAria: "Axtar",
    notFound__backToHome: "Ana səhifəyə qayıt",
    faq__breadcrumbTitle: "FAQ",
    faq__headline: "Tez-tez verilən suallar",
    faq__intro:
      "Aşağıdakı suallara cavab tapa bilərsiniz. Əlavə sualınız olarsa bizimlə əlaqə saxlayın.",
    contact__breadcrumbTitle: "Əlaqə",
    contact__mapTitle: "Xəritə",
    contact__addressLine1: "Ünvan buradadır,",
    contact__addressLine2: "küçə, kəsişmə 123.",
    contact__followUs: "Bizi izləyin",
    contact__facebook: "Facebook",
    contact__twitter: "Twitter",
    contact__youtube: "YouTube",
    contact__googlePlus: "Google Plus",
    contact__instagram: "Instagram",
    contact__getInTouch: "Bizimlə əlaqə",
    contact__name: "Ad",
    contact__email: "Email",
    contact__subject: "Mövzu",
    contact__yourMessage: "Mesajınız",
    contact__send: "GÖNDƏR",
    cart__breadcrumbTitle: "Səbət",
    cart__delete: "Sil",
    cart__image: "Şəkil",
    cart__product: "Məhsul",
    cart__price: "Qiymət",
    cart__total: "Cəmi",
    cart__empty: "Səbət boşdur",
    cart__update: "Səbəti yenilə",
    cart__totals: "Səbət yekunu",
    cart__subtotal: "Aralıq cəm",
    cart__proceedToCheckout: "Sifarişə keç",
  },
  ru: {
    header__topWelcomeText: "Добро пожаловать в наш магазин!",
    "header__topLink__login": "Вход",
    "header__topLink__register": "Регистрация",
    "header__topLink__my-account": "Мой аккаунт",
    "header__topLink__admin-panel": "Админ панель",
    header__logout: "Выйти",
    header__searchPlaceholder: "OEM...",
    directorLoginBanner__sectionHead__button: "Продолжить",
    breadcrumb__home: "Главная",
    breadcrumb__products: "Товары",
    common__loading: "Загрузка...",
    common__noResults: "Ничего не найдено",
    common__required: "Обязательно",
    common__increase: "Увеличить",
    common__decrease: "Уменьшить",
    common__productAlt: "Товар",
    pagination__previous: "Назад",
    pagination__next: "Вперед",
    catalog__oemLabel: "OEM:",
    catalog__similarFallbackMessage: "Точный товар не найден, показываем похожие результаты OEM.",
    catalog__emptyMessage: "Товар не найден",
    catalog__filterTitle: "Фильтр",
    catalog__categoryPlaceholder: "Категория",
    catalog__brandPlaceholder: "Бренд",
    catalog__markPlaceholder: "Марка",
    catalog__modelPlaceholder: "Модель",
    catalog__searchPlaceholder: "Поиск",
    catalog__searchButton: "Поиск",
    catalog__clearButton: "Очистить",
    catalogList__searchTitle: "Поиск",
    catalogList__searchByNamePlaceholder: "Поиск по названию",
    catalogList__categoriesTitle: "Категории",
    catalogList__showingResults: "Показано результатов: {count}",
    offers__brandLabel: "Бренд",
    offers__all: "Все",
    offers__search: "Поиск",
    offers__reset: "Сброс",
    offers__detail: "Деталь",
    offers__warehouse: "Склад",
    offers__price: "Цена",
    offers__add: "ДОБАВИТЬ",
    offerModal__qtyLabel: "Количество",
    offerModal__amountLabel: "Сумма",
    offerModal__noteLabel: "Если есть примечания, добавьте их.",
    offerModal__deliveryDateLabel: "Дата доставки:",
    offerModal__deliveryDateValue: "30 апреля",
    offerModal__addToCart: "В КОРЗИНУ",
    offerModal__addedToCartToast: "Успешно добавлено в корзину",
    addToCartModal__successMessage: "Успешно добавлено в корзину!",
    addToCartModal__viewCart: "Корзина",
    addToCartModal__checkout: "Оформить",
    addToCartModal__itemsInCart: "В вашей корзине {count} товаров.",
    addToCartModal__totalPriceLabel: "ИТОГО:",
    addToCartModal__continueShopping: "ПРОДОЛЖИТЬ ПОКУПКИ",
    product__similarBadge: "Похожий OEM",
    product__viewOffersAria: "Посмотреть предложения",
    product__listDescriptionMock:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad, iure incidunt. Ab consequatur temporibus non eveniet inventore doloremque necessitatibus sed, ducimus quisquam, ad asperiores",
    productDetails__brand: "Бренд",
    productDetails__mark: "Марка",
    productDetails__model: "Модель",
    productDetails__code: "Код",
    productDetails__oem: "OEM",
    productDetails__similarOem: "Похожие OEM",
    productDetailsPage__notFound: "Товар не найден",
    notFound__breadcrumbTitle: "404",
    notFound__headline: "Страница не найдена",
    notFound__messageLine1: "Извините, страница не найдена,",
    notFound__messageLine2: "возможно удалена, переименована или временно недоступна.",
    notFound__searchPlaceholder: "Поиск по сайту ...",
    notFound__searchAria: "Поиск",
    notFound__backToHome: "На главную",
    faq__breadcrumbTitle: "FAQ",
    faq__headline: "Часто задаваемые вопросы",
    faq__intro: "Ниже вы найдете ответы на часто задаваемые вопросы.",
    contact__breadcrumbTitle: "Контакты",
    contact__mapTitle: "Карта",
    contact__addressLine1: "Адрес здесь,",
    contact__addressLine2: "улица, перекресток 123.",
    contact__followUs: "Подписывайтесь",
    contact__facebook: "Facebook",
    contact__twitter: "Twitter",
    contact__youtube: "YouTube",
    contact__googlePlus: "Google Plus",
    contact__instagram: "Instagram",
    contact__getInTouch: "Связаться с нами",
    contact__name: "Имя",
    contact__email: "Email",
    contact__subject: "Тема",
    contact__yourMessage: "Ваше сообщение",
    contact__send: "ОТПРАВИТЬ",
    cart__breadcrumbTitle: "Корзина",
    cart__delete: "Удалить",
    cart__image: "Изображение",
    cart__product: "Товар",
    cart__price: "Цена",
    cart__total: "Итого",
    cart__empty: "Корзина пуста",
    cart__update: "Обновить корзину",
    cart__totals: "Итого по корзине",
    cart__subtotal: "Промежуточный итог",
    cart__proceedToCheckout: "Перейти к оформлению",
  },
};
