export const STATIC_CONTENT_MOCK = {
  en: {
    header__topWelcomeText: "Welcome to our store!",
    "header__topLink__login": "Login",
    "header__topLink__register": "Register",
    "header__topLink__my-account": "My Account",
    "header__topLink__admin-panel": "Admin Panel",
    header__logout: "Logout",
    header__searchPlaceholder: "OEM...",
    directorLoginBanner__sectionHead__button: "Continue",
    breadcrumb__home: "Home",
    breadcrumb__products: "Products",
    common__loading: "Loading...",
    common__noResults: "No results found",
    common__required: "Required",
    common__increase: "Increase",
    common__decrease: "Decrease",
    common__productAlt: "Product",
    pagination__previous: "Previous",
    pagination__next: "Next",
    catalog__oemLabel: "OEM:",
    catalog__similarFallbackMessage: "No exact product found, showing similar OEM results.",
    catalog__emptyMessage: "Product not found",
    catalog__filterTitle: "Filter",
    catalog__categoryPlaceholder: "Category",
    catalog__brandPlaceholder: "Brand",
    catalog__markPlaceholder: "Mark",
    catalog__modelPlaceholder: "Model",
    catalog__searchPlaceholder: "Search",
    catalog__searchButton: "Search",
    catalog__clearButton: "Clear",
    catalogList__searchTitle: "Search",
    catalogList__searchByNamePlaceholder: "Search by name",
    catalogList__categoriesTitle: "Categories",
    catalogList__showingResults: "Showing {count} results",
    offers__brandLabel: "Brand",
    offers__all: "All",
    offers__search: "Search",
    offers__reset: "Reset",
    offers__detail: "Detail",
    offers__warehouse: "Warehouse",
    offers__price: "Price",
    offers__add: "ADD",
    offerModal__qtyLabel: "Quantity",
    offerModal__amountLabel: "Amount",
    offerModal__noteLabel: "If you have notes, enter them.",
    offerModal__deliveryDateLabel: "Delivery date:",
    offerModal__deliveryDateValue: "30 April",
    offerModal__addToCart: "ADD TO CART",
    offerModal__addedToCartToast: "Added to cart successfully",
    addToCartModal__successMessage: "Added to cart successfully!",
    addToCartModal__viewCart: "View Cart",
    addToCartModal__checkout: "Checkout",
    addToCartModal__itemsInCart: "There are {count} items in your cart.",
    addToCartModal__totalPriceLabel: "TOTAL PRICE:",
    addToCartModal__continueShopping: "CONTINUE SHOPPING",
    product__similarBadge: "Similar OEM",
    product__viewOffersAria: "View offers",
    product__listDescriptionMock:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad, iure incidunt. Ab consequatur temporibus non eveniet inventore doloremque necessitatibus sed, ducimus quisquam, ad asperiores",
    productDetails__brand: "Brand",
    productDetails__mark: "Mark",
    productDetails__model: "Model",
    productDetails__code: "Code",
    productDetails__oem: "OEM",
    productDetails__similarOem: "Similar OEM",
    productDetailsPage__notFound: "Product not found",
    notFound__breadcrumbTitle: "404 Pages",
    notFound__headline: "Opps! PAGE NOT BE FOUND",
    notFound__messageLine1: "Sorry but the page you are looking for does not exist, have been",
    notFound__messageLine2: "removed, name changed or is temporarily unavailable.",
    notFound__searchPlaceholder: "Search entire store here ...",
    notFound__searchAria: "Search",
    notFound__backToHome: "Back to home page",
    faq__breadcrumbTitle: "FAQ",
    faq__headline: "Below are frequently asked questions, you may find the answer for yourself",
    faq__intro:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id erat sagittis, faucibus metus malesuada, eleifend turpis. Mauris semper augue id nisl aliquet, a porta lectus mattis. Nulla at tortor augue. In eget enim diam. Donec gravida tortor sem, ac fermentum nibh rutrum sit amet. Nulla convallis mauris vitae congue consequat. Donec interdum nunc purus, vitae vulputate arcu fringilla quis. Vivamus iaculis euismod dui.",
    contact__breadcrumbTitle: "Contact Us",
    contact__mapTitle: "Map",
    contact__addressLine1: "Address goes here,",
    contact__addressLine2: "street, Crossroad 123.",
    contact__followUs: "Follow Us",
    contact__facebook: "Facebook",
    contact__twitter: "Twitter",
    contact__youtube: "YouTube",
    contact__googlePlus: "Google Plus",
    contact__instagram: "Instagram",
    contact__getInTouch: "Get In Touch",
    contact__name: "Name",
    contact__email: "Email",
    contact__subject: "Subject",
    contact__yourMessage: "Your Message",
    contact__send: "SEND",
    cart__breadcrumbTitle: "Cart",
    cart__delete: "Delete",
    cart__image: "Image",
    cart__product: "Product",
    cart__price: "Price",
    cart__total: "Total",
    cart__empty: "Cart is empty",
    cart__update: "update cart",
    cart__totals: "Cart Totals",
    cart__subtotal: "Subtotal",
    cart__proceedToCheckout: "Proceed to Checkout",
    nav__main__home: "Home",
    nav__main__products: "Products",
    nav__main__brands: "Brands",
    "nav__main__about-us": "About Us",
    "nav__main__contact-us": "Contact Us",
    footer__logoAlt: "Logo",
    footer__aboutText: "We are a team of designers and developers that create high quality Magento, Prestashop, Opencart...",
    footer__customerSupport: "Customer Support",
    footer__subscribeTitle: "Subscribe newsletter to get updated",
    footer__subscribePlaceholder: "Search entire store here ...",
    footer__subscribeButton: "Subscribe",
    footer__subscribeNoteLine1: "We’ll never share your email address",
    footer__subscribeNoteLine2: "with a third-party.",
    footer__informationTitle: "Information",
    footer__pinterest: "Pinterest",
    footer__copyright: "Copyright",
    footer__paymentMethodsAria: "Payment methods",
    footer__infoLink__delivery: "Delivery",
    "footer__infoLink__about-us": "About Us",
    "footer__infoLink__contact-us": "Contact us",
    footer__infoLink__stores: "Stores",
    "footer__accountLink__legal-notice": "Legal Notice",
    "footer__accountLink__secure-payment": "Secure payment",
    footer__accountLink__sitemap: "Sitemap",
    "footer__accountLink__my-account": "My Account",
    home__popularCategoriesTitle: "Popular Categories",
    home__allCategoriesLink: "All Categories",
    home__productsSectionTitle: "Products",
    carousel__previous: "Previous products",
    carousel__next: "Next products",
    mobile__settings: "Setting",
    mobile__shoppingCart: "Shopping Cart",
    mobile__searchPlaceholder: "Type OEM code...",
    "home__hero__home1-hero-1__eyebrow": "World Best Quality",
    "home__hero__home1-hero-1__title": "New Car Parts",
    "home__hero__home1-hero-1__description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiu",
    "home__hero__home1-hero-1__ctaLabel": "Shopping Now",
    "home__hero__home1-hero-2__eyebrow": "World Best Quality",
    "home__hero__home1-hero-2__title": "New Car Parts",
    "home__hero__home1-hero-2__description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiu",
    "home__hero__home1-hero-2__ctaLabel": "Shopping Now",
    "home__banner__banner-1__eyebrow": "Car Wheel",
    "home__banner__banner-1__title": "30% Off",
    "home__banner__banner-1__ctaLabel": "Shop Now",
    "home__banner__banner-2__eyebrow": "Car Vails",
    "home__banner__banner-2__title": "40% Off",
    "home__banner__banner-2__ctaLabel": "Shop Now",
    "home__banner__banner-3__eyebrow": "Car Vails",
    "home__banner__banner-3__title": "50% Off",
    "home__banner__banner-3__ctaLabel": "Shop Now",
  },
  az: {
    header__topWelcomeText: "Mağazamıza xoş gəlmisiniz!",
    "header__topLink__login": "Daxil ol",
    "header__topLink__register": "Qeydiyyat",
    "header__topLink__my-account": "Hesabım",
    "header__topLink__admin-panel": "Admin Panel",
    header__logout: "Çıxış",
    header__searchPlaceholder: "OEM...",
    directorLoginBanner__sectionHead__button: "Davam et",
    breadcrumb__home: "Ana səhifə",
    breadcrumb__products: "Məhsullar",
    common__loading: "Yüklənir...",
    common__noResults: "Nəticə tapılmadı",
    common__required: "Mütləqdir",
    common__increase: "Artır",
    common__decrease: "Azalt",
    common__productAlt: "Məhsul",
    pagination__previous: "Əvvəlki",
    pagination__next: "Növbəti",
    catalog__oemLabel: "OEM:",
    catalog__similarFallbackMessage: "Uyğun məhsul tapılmadı, oxşar OEM nəticələri göstərilir.",
    catalog__emptyMessage: "Məhsul tapılmadı",
    catalog__filterTitle: "Filter",
    catalog__categoryPlaceholder: "Kateqoriya",
    catalog__brandPlaceholder: "Brend",
    catalog__markPlaceholder: "Marka",
    catalog__modelPlaceholder: "Model",
    catalog__searchPlaceholder: "Axtarış",
    catalog__searchButton: "Axtar",
    catalog__clearButton: "Təmizlə",
    catalogList__searchTitle: "Axtarış",
    catalogList__searchByNamePlaceholder: "Ada görə axtar",
    catalogList__categoriesTitle: "Kateqoriyalar",
    catalogList__showingResults: "{count} nəticə göstərilir",
    offers__brandLabel: "Brend",
    offers__all: "Hamısı",
    offers__search: "Axtar",
    offers__reset: "Sıfırla",
    offers__detail: "Detal",
    offers__warehouse: "Anbar",
    offers__price: "Qiymət",
    offers__add: "ƏLAVƏ ET",
    offerModal__qtyLabel: "Miqdar",
    offerModal__amountLabel: "Məbləğ",
    offerModal__noteLabel: "Qeydləriniz varsa daxil edin.",
    offerModal__deliveryDateLabel: "Çatdırılma tarixi:",
    offerModal__deliveryDateValue: "30 aprelə",
    offerModal__addToCart: "SƏBƏTƏ AT",
    offerModal__addedToCartToast: "Səbətə uğurla əlavə edildi",
    addToCartModal__successMessage: "Səbətə uğurla əlavə edildi!",
    addToCartModal__viewCart: "Səbətə bax",
    addToCartModal__checkout: "Sifariş et",
    addToCartModal__itemsInCart: "Səbətdə {count} məhsul var.",
    addToCartModal__totalPriceLabel: "CƏM MƏBLƏĞ:",
    addToCartModal__continueShopping: "ALIŞVERİŞƏ DAVAM ET",
    product__similarBadge: "Oxşar OEM",
    product__viewOffersAria: "Təkliflərə bax",
    product__listDescriptionMock:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad, iure incidunt. Ab consequatur temporibus non eveniet inventore doloremque necessitatibus sed, ducimus quisquam, ad asperiores",
    productDetails__brand: "Brend",
    productDetails__mark: "Marka",
    productDetails__model: "Model",
    productDetails__code: "Kod",
    productDetails__oem: "OEM",
    productDetails__similarOem: "Oxşar OEM",
    productDetailsPage__notFound: "Məhsul tapılmadı",
    notFound__breadcrumbTitle: "404 Səhifə",
    notFound__headline: "Səhifə tapılmadı",
    notFound__messageLine1: "Axtardığınız səhifə mövcud deyil,",
    notFound__messageLine2: "silinib, adı dəyişdirilib və ya müvəqqəti əlçatmazdır.",
    notFound__searchPlaceholder: "Sayt üzrə axtar ...",
    notFound__searchAria: "Axtar",
    notFound__backToHome: "Ana səhifəyə qayıt",
    faq__breadcrumbTitle: "FAQ",
    faq__headline: "Tez-tez verilən suallar",
    faq__intro:
      "Aşağıdakı suallara cavab tapa bilərsiniz. Əlavə sualınız olarsa bizimlə əlaqə saxlayın.",
    contact__breadcrumbTitle: "Əlaqə",
    contact__mapTitle: "Xəritə",
    contact__addressLine1: "Ünvan buradadır,",
    contact__addressLine2: "küçə, kəsişmə 123.",
    contact__followUs: "Bizi izləyin",
    contact__facebook: "Facebook",
    contact__twitter: "Twitter",
    contact__youtube: "YouTube",
    contact__googlePlus: "Google Plus",
    contact__instagram: "Instagram",
    contact__getInTouch: "Bizimlə əlaqə",
    contact__name: "Ad",
    contact__email: "Email",
    contact__subject: "Mövzu",
    contact__yourMessage: "Mesajınız",
    contact__send: "GÖNDƏR",
    cart__breadcrumbTitle: "Səbət",
    cart__delete: "Sil",
    cart__image: "Şəkil",
    cart__product: "Məhsul",
    cart__price: "Qiymət",
    cart__total: "Cəmi",
    cart__empty: "Səbət boşdur",
    cart__update: "Səbəti yenilə",
    cart__totals: "Səbət yekunu",
    cart__subtotal: "Aralıq cəm",
    cart__proceedToCheckout: "Sifarişə keç",
    nav__main__home: "Ana səhifə",
    nav__main__products: "Məhsullar",
    nav__main__brands: "Brendlər",
    "nav__main__about-us": "Haqqımızda",
    "nav__main__contact-us": "Əlaqə",
    footer__logoAlt: "Loqo",
    footer__aboutText: "Biz yüksək keyfiyyətli məhsullar təqdim edən komanda kimi çalışırıq.",
    footer__customerSupport: "Müştəri dəstəyi",
    footer__subscribeTitle: "Yeniliklər üçün abunə olun",
    footer__subscribePlaceholder: "Email daxil edin ...",
    footer__subscribeButton: "Abunə ol",
    footer__subscribeNoteLine1: "Email ünvanınızı heç vaxt paylaşmırıq",
    footer__subscribeNoteLine2: "üçüncü tərəflərlə.",
    footer__informationTitle: "Məlumat",
    footer__pinterest: "Pinterest",
    footer__copyright: "Müəllif hüquqları",
    footer__paymentMethodsAria: "Ödəniş üsulları",
    footer__infoLink__delivery: "Çatdırılma",
    "footer__infoLink__about-us": "Haqqımızda",
    "footer__infoLink__contact-us": "Əlaqə",
    footer__infoLink__stores: "Mağazalar",
    "footer__accountLink__legal-notice": "Hüquqi qeyd",
    "footer__accountLink__secure-payment": "Təhlükəsiz ödəniş",
    footer__accountLink__sitemap: "Sayt xəritəsi",
    "footer__accountLink__my-account": "Hesabım",
    home__popularCategoriesTitle: "Populyar kateqoriyalar",
    home__allCategoriesLink: "Bütün kateqoriyalar",
    home__productsSectionTitle: "Məhsullar",
    carousel__previous: "Əvvəlki məhsullar",
    carousel__next: "Növbəti məhsullar",
    mobile__settings: "Tənzimləmə",
    mobile__shoppingCart: "Səbət",
    mobile__searchPlaceholder: "OEM kod yazın...",
    "home__hero__home1-hero-1__eyebrow": "Ən yaxşı keyfiyyət",
    "home__hero__home1-hero-1__title": "Yeni avtomobil hissələri",
    "home__hero__home1-hero-1__description": "Lorem ipsum dolor sit amet",
    "home__hero__home1-hero-1__ctaLabel": "İndi alış-veriş et",
    "home__hero__home1-hero-2__eyebrow": "Ən yaxşı keyfiyyət",
    "home__hero__home1-hero-2__title": "Yeni avtomobil hissələri",
    "home__hero__home1-hero-2__description": "Lorem ipsum dolor sit amet",
    "home__hero__home1-hero-2__ctaLabel": "İndi alış-veriş et",
    "home__banner__banner-1__eyebrow": "Avtomobil təkəri",
    "home__banner__banner-1__title": "30% endirim",
    "home__banner__banner-1__ctaLabel": "İndi al",
    "home__banner__banner-2__eyebrow": "Avtomobil aksesuarı",
    "home__banner__banner-2__title": "40% endirim",
    "home__banner__banner-2__ctaLabel": "İndi al",
    "home__banner__banner-3__eyebrow": "Avtomobil aksesuarı",
    "home__banner__banner-3__title": "50% endirim",
    "home__banner__banner-3__ctaLabel": "İndi al",
  },
  ru: {
    header__topWelcomeText: "Добро пожаловать в наш магазин!",
    "header__topLink__login": "Вход",
    "header__topLink__register": "Регистрация",
    "header__topLink__my-account": "Мой аккаунт",
    "header__topLink__admin-panel": "Админ панель",
    header__logout: "Выйти",
    header__searchPlaceholder: "OEM...",
    directorLoginBanner__sectionHead__button: "Продолжить",
    breadcrumb__home: "Главная",
    breadcrumb__products: "Товары",
    common__loading: "Загрузка...",
    common__noResults: "Ничего не найдено",
    common__required: "Обязательно",
    common__increase: "Увеличить",
    common__decrease: "Уменьшить",
    common__productAlt: "Товар",
    pagination__previous: "Назад",
    pagination__next: "Вперед",
    catalog__oemLabel: "OEM:",
    catalog__similarFallbackMessage: "Точный товар не найден, показываем похожие результаты OEM.",
    catalog__emptyMessage: "Товар не найден",
    catalog__filterTitle: "Фильтр",
    catalog__categoryPlaceholder: "Категория",
    catalog__brandPlaceholder: "Бренд",
    catalog__markPlaceholder: "Марка",
    catalog__modelPlaceholder: "Модель",
    catalog__searchPlaceholder: "Поиск",
    catalog__searchButton: "Поиск",
    catalog__clearButton: "Очистить",
    catalogList__searchTitle: "Поиск",
    catalogList__searchByNamePlaceholder: "Поиск по названию",
    catalogList__categoriesTitle: "Категории",
    catalogList__showingResults: "Показано результатов: {count}",
    offers__brandLabel: "Бренд",
    offers__all: "Все",
    offers__search: "Поиск",
    offers__reset: "Сброс",
    offers__detail: "Деталь",
    offers__warehouse: "Склад",
    offers__price: "Цена",
    offers__add: "ДОБАВИТЬ",
    offerModal__qtyLabel: "Количество",
    offerModal__amountLabel: "Сумма",
    offerModal__noteLabel: "Если есть примечания, добавьте их.",
    offerModal__deliveryDateLabel: "Дата доставки:",
    offerModal__deliveryDateValue: "30 апреля",
    offerModal__addToCart: "В КОРЗИНУ",
    offerModal__addedToCartToast: "Успешно добавлено в корзину",
    addToCartModal__successMessage: "Успешно добавлено в корзину!",
    addToCartModal__viewCart: "Корзина",
    addToCartModal__checkout: "Оформить",
    addToCartModal__itemsInCart: "В вашей корзине {count} товаров.",
    addToCartModal__totalPriceLabel: "ИТОГО:",
    addToCartModal__continueShopping: "ПРОДОЛЖИТЬ ПОКУПКИ",
    product__similarBadge: "Похожий OEM",
    product__viewOffersAria: "Посмотреть предложения",
    product__listDescriptionMock:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    productDetails__brand: "Бренд",
    productDetails__mark: "Марка",
    productDetails__model: "Модель",
    productDetails__code: "Код",
    productDetails__oem: "OEM",
    productDetails__similarOem: "Похожие OEM",
    productDetailsPage__notFound: "Товар не найден",
    notFound__breadcrumbTitle: "404",
    notFound__headline: "Страница не найдена",
    notFound__messageLine1: "Извините, страница не найдена,",
    notFound__messageLine2: "возможно удалена, переименована или временно недоступна.",
    notFound__searchPlaceholder: "Поиск по сайту ...",
    notFound__searchAria: "Поиск",
    notFound__backToHome: "На главную",
    faq__breadcrumbTitle: "FAQ",
    faq__headline: "Часто задаваемые вопросы",
    faq__intro: "Ниже вы найдете ответы на часто задаваемые вопросы.",
    contact__breadcrumbTitle: "Контакты",
    contact__mapTitle: "Карта",
    contact__addressLine1: "Адрес здесь,",
    contact__addressLine2: "улица, перекресток 123.",
    contact__followUs: "Подписывайтесь",
    contact__facebook: "Facebook",
    contact__twitter: "Twitter",
    contact__youtube: "YouTube",
    contact__googlePlus: "Google Plus",
    contact__instagram: "Instagram",
    contact__getInTouch: "Связаться с нами",
    contact__name: "Имя",
    contact__email: "Email",
    contact__subject: "Тема",
    contact__yourMessage: "Ваше сообщение",
    contact__send: "ОТПРАВИТЬ",
    cart__breadcrumbTitle: "Корзина",
    cart__delete: "Удалить",
    cart__image: "Изображение",
    cart__product: "Товар",
    cart__price: "Цена",
    cart__total: "Итого",
    cart__empty: "Корзина пуста",
    cart__update: "Обновить корзину",
    cart__totals: "Итого по корзине",
    cart__subtotal: "Промежуточный итог",
    cart__proceedToCheckout: "Перейти к оформлению",
    nav__main__home: "Главная",
    nav__main__products: "Товары",
    nav__main__brands: "Бренды",
    "nav__main__about-us": "О нас",
    "nav__main__contact-us": "Контакты",
    footer__logoAlt: "Логотип",
    footer__aboutText: "Мы команда, которая создает качественные решения и продукты.",
    footer__customerSupport: "Поддержка",
    footer__subscribeTitle: "Подпишитесь на новости",
    footer__subscribePlaceholder: "Введите email ...",
    footer__subscribeButton: "Подписаться",
    footer__subscribeNoteLine1: "Мы никогда не передаем ваш email",
    footer__subscribeNoteLine2: "третьим лицам.",
    footer__informationTitle: "Информация",
    footer__pinterest: "Pinterest",
    footer__copyright: "Авторские права",
    footer__paymentMethodsAria: "Способы оплаты",
    footer__infoLink__delivery: "Доставка",
    "footer__infoLink__about-us": "О нас",
    "footer__infoLink__contact-us": "Контакты",
    footer__infoLink__stores: "Магазины",
    "footer__accountLink__legal-notice": "Правовая информация",
    "footer__accountLink__secure-payment": "Безопасная оплата",
    footer__accountLink__sitemap: "Карта сайта",
    "footer__accountLink__my-account": "Мой аккаунт",
    home__popularCategoriesTitle: "Популярные категории",
    home__allCategoriesLink: "Все категории",
    home__productsSectionTitle: "Товары",
    carousel__previous: "Предыдущие товары",
    carousel__next: "Следующие товары",
    mobile__settings: "Настройки",
    mobile__shoppingCart: "Корзина",
    mobile__searchPlaceholder: "Введите OEM код...",
    "home__hero__home1-hero-1__eyebrow": "Лучшее качество",
    "home__hero__home1-hero-1__title": "Новые автозапчасти",
    "home__hero__home1-hero-1__description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiu",
    "home__hero__home1-hero-1__ctaLabel": "К покупкам",
    "home__hero__home1-hero-2__eyebrow": "Лучшее качество",
    "home__hero__home1-hero-2__title": "Новые автозапчасти",
    "home__hero__home1-hero-2__description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiu",
    "home__hero__home1-hero-2__ctaLabel": "К покупкам",
    "home__banner__banner-1__eyebrow": "Колеса",
    "home__banner__banner-1__title": "Скидка 30%",
    "home__banner__banner-1__ctaLabel": "Купить",
    "home__banner__banner-2__eyebrow": "Аксессуары",
    "home__banner__banner-2__title": "Скидка 40%",
    "home__banner__banner-2__ctaLabel": "Купить",
    "home__banner__banner-3__eyebrow": "Аксессуары",
    "home__banner__banner-3__title": "Скидка 50%",
    "home__banner__banner-3__ctaLabel": "Купить",
  },
};
